### ISSUE TITLE
tell a story about the project. 

### ISSUE THREAD

**Issue by kohlhase** [UFrameIT/UFrameIT.github.io#1]
We should have something like a project history, I am writing this down; you can directly use the source.  But test for dangling links. 
=============8<----------------------

UFrameIT is a framework for building serious games by combining the exploration of virtual worlds with logic-based knowledge management. 

The UFrameIT project initiated by the [KWARC Research Group](https://kwarc.info) at [FAU Erlangen-Nürnberg](https://fau.de). 

#### The [Jacobs University](https://jacobs-university.de) Phase

The idea behind UFrameIT (using MMT pushouts for scroll application) was already formulated in a [paper in 2012](http://kwarc.info/kohlhase/submit/activeex-2012.pdf).
A very first version was implemented in [a 2013 bachelor thesis](https://gl.kwarc.info/supervision/BSc-archive/blob/master/2013/rachev_daniel.pdf).
2015/6 Denis Rochau gave a complete implementation based on the [Unreal Engine](https://www.unrealengine.com) ([Bachelor's Thesis](https://gl.kwarc.info/supervision/BSc-archive/blob/master/2016/rochau_denis.pdf); [CICM Work-in-Progress Paper](http://ceur-ws.org/Vol-1785/W50.pdf),  [demo video](https://gl.kwarc.info/FrameIT/CICM16-WiP/-/blob/master/Screen%2005-12-2016%2020-17-23.avi).

#### UFrameIT at [FAU Erlangen-Nürnberg](https:.//fau.de)

After a long period, where students got frustrated with the complexities of the unreal engine and its documentation, a group for FAU students got together in late 2019 to restart the project using the [unity game engine](https://unity.com) as a basis. The UFrameIT framework is the result of this effort.

**Comment by richardmarcus** [comment]
Done
