### ISSUE TITLE
mention project resources

### ISSUE THREAD

**Issue by kohlhase** [UFrameIT/UFrameIT.github.io#3]
* The implementation split up in two repositories (and a sentence saying why this is so)
* The demo videos (see the link to the old one in #1)
* the publications: https://kwarc.github.io/bibs/frameit
* the KWARC project page for FrameIT https://kwarc.info/systems/frameit

**Comment by richardmarcus** [comment]
1) UFrameIT <> Server or FrameIT(mathhub) <> UFrameIT(github) or both or as I have written it?
2) done
3) done
4) done

**Comment by kohlhase** [comment]
very good, I have restructured a bit.
